/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const todolists_Validation = require('./code/todolists-validation');

class todoListSrv extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'TodoLists', async (request) => {
            await todolists_Validation(request);
        });

        return super.init();
    }
}


module.exports = {
    todoListSrv
};